### ISSUE TITLE
detected Trojan

### ISSUE THREAD

**Issue by rafalbieniek** [pza007/wfrp_4_npc_generator#2]
Detected Trojan:Win32/Wacatac.B!ml

containerfile: C:\Users\rbien\OneDrive\Dokumenty\wfrp_4_npc_generator-main.zip

file: C:\Users\rbien\OneDrive\Dokumenty\wfrp_4_npc_generator-main.zip->wfrp_4_npc_generator-main/main.exe

webfile: C:\Users\rbien\OneDrive\Dokumenty\wfrp_4_npc_generator-main.zip|https://codeload.github.com/pza007/wfrp_4_npc_generator/zip/refs/heads/main|pid:17936,ProcessStart:133165491127627701

**Comment by pza007** [comment]
Fixed with latest commit.
